#!/bin/bash
set -eua


# LIBS_N        = -L$(CORELIB) -lsp_d -lnemsio -lgfsio_4 -lbacio_4 -lsigio_4 \
#               -lsfcio_4 -lbufr_d_64 -lw3nco_d -lw3emc_d -lcrtm_v2.0.6 $(WRFLIB) \
#               -L$(NETCDFPATH)/lib -lnetcdf


module load ESMF/310rp5 
module load bacio/v2.0.1
module load nemsio/v2.2.1
module load sp/v2.0.2
module load w3emc/v2.2.0
module load w3nco/v2.0.6
module load NetCDF/3.6.3
module load bufr/v11.0.1
module load ip/v2.0.0
module load sfcio/v1.0.0
module load sigio/v2.0.1
module load ibmpe/1.3.0.12
module load ics/12.1
module load landsfcutil/v2.0.0
module load crtm/v2.0.6            
module load gfsio

module list
