#!/bin/ksh
set -xa

export PS4='$SECONDS + '
date

# #### 06/12/2006 ##############################################
# SETUP CDAS TROPICAL CYCLONE QC/RELOCATION PROCESSING VARIABLES
# ##############################################################

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00

##########################
# Specify NET and RUN Name
##########################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY

##########################################################
# define cfs directories/scripts/executables            
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm 
export USHcfs=$HOMEcfs/ush  
export FIXcfs=$HOMEcfs/fix  

export HOMEdump=$HOMEcfs
export HOMEobsproc_dump=$HOMEcfs 

##############################################
# Define COM directories
##############################################
export COMROT=$COMROOT/${NET}/${envir}
export  COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
mkdir -m 755 -p $COMOUT

export COM_GDAS=${COM_GDAS:-/gpfs/hps/nco/ops/com/gfs/prod}
export TANK_GRIBFLDS=${TANK_GRIBFLDS:-$DCOMROOT}             
export COM_SSTOIQD=${COM_SSTOIQD:-/com/omb/prod/sstoiqd}
export COM_ENGICE=${COM_ENGICE:-/com2/omb/prod/sice}
export COMGDAS=$COM_GDAS/gdas.${PDY}/$cyc


########################################################################
# execute the script
# Set DUMP_FROM_PROD to NO if getting the dump files from /global/dump
########################################################################

export DUMP_FROM_PROD=${DUMP_FROM_PROD:-YES}

if [ "$DUMP_FROM_PROD" = NO ]
then
  ${DUMPDV:-$HOMEcfs/scripts/excfs_hpss_dump.sh.ecf} 
else
  ${DUMPSH:-$HOMEcfs/scripts/excfs_cdas_dump.sh.ecf}
fi

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT  
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

