#!/bin/bash

set -euax

####################################
# Specify NET and RUN Name and model
####################################
export NET=cfs
export RUN=cdas

export host=${host:-`hostname | cut -c1`}

###############################################

date
export PS4='$SECONDS + '

# #############################################
# SETUP CLDAS PREP PROCESSING VARIABLES
# ##############################################

##########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# VERBOSE  - Specify Verbose Output
####################################
export VERBOSE=${VERBOSE:-YES}

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY

export CDATE=${PDY}${cyc}
export GETPRECIP_FROM_CPC=${GETPRECIP_FROM_CPC:-NO}

##########################################################
# define cfs directories/scripts/executables
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm
export USHcfs=$HOMEcfs/ush
export EXECcfs=$HOMEcfs/exec
export FIXcfs=$HOMEcfs/fix
export FIX_LM=$FIXcfs/cfs_fix_lm

##############################################
# Define COM directories
##############################################
export COMROT=$(compath.py ${NET}/${cfs_ver})
export  COMIN=$(compath.py ${NET}/${cfs_ver}/${RUN}.${PDY})
export COMOUT=$(compath.py -o ${NET}/${cfs_ver}/${RUN}.${PDY})
mkdir -m775 -p $COMOUT

export COMCDAS=${COMCDAS:-$(compath.py -o ${NET}/${cfs_ver})}
export DCOMIN=${DCOMIN:-${DCOMROOT}}

export COMOUTGLDAS=$COMROT/cmap/gldas
export COMOUTCMAP=$COMROT/cmap/pentad
export COMOUTGAGE=$COMROT/cmap/gauge

mkdir -m 775 -p $COMOUTGLDAS $COMOUTCMAP $COMOUTGAGE $COMOUT

#############################################################
# execute the script
#############################################################

${PREPCIPLISSSH:-$HOMEcfs/scripts/excfs_cdas_preciplis.sh}
err=$?; err_chk

#cat $pgmout

msg="ENDED NORMALLY."
postmsg "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

