#!/bin/ksh

set -xa

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd1
# DEV_ECF: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
#####################################################################################

####################################
# Specify NET and RUN Name and model
####################################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

export host=${host:-`hostname | cut -c1`}
export jlogfile=${jlogfile:-/dev/null}

date
export PS4='$SECONDS + '

# #############################################
# SETUP CLDAS PREP PROCESSING VARIABLES
# ##############################################

##########################################################
# obtain unique process id (pid) and make temp directory
##########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY
export CDATE=${PDY}${cyc}

##########################################################
# define cfs directories/scripts/executables            
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm 
export USHcfs=$HOMEcfs/ush  
export FIXcfs=$HOMEcfs/fix  

##############################################
# Define COM directories
##############################################
export COMROT=$COMROOT/${NET}/${envir}
export  COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
mkdir -m775 -p $COMOUT

##############################################
# Define OMP_NUM_THREADS
##############################################
export OMP_NUM_THREADS=1

env

#############################################################
# execute the script

${CLDASSH:-$HOMEcfs/scripts/excfs_cdas_gldas.sh}

#############################################################
cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

