#!/bin/ksh
set -xa


####################################
# Specify NET and RUN Name and model
####################################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

export host=${host:-`hostname | cut -c1`}
export jlogfile=${jlogfile:-/dev/null}

date
export PS4='$SECONDS + '

# #############################################
# SETUP FITS TO OBS PROCESSING VARIABLES
# ##############################################

##########################################################
# obtain unique process id (pid) and make temp directory
##########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# VERBOSE  - Specify Verbose Output 
####################################
export VERBOSE=${VERBOSE:-YES}

##########################################################
# define cfs directories/scripts/executables            
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm 
export USHcfs=$HOMEcfs/ush  
export FIXcfs=$HOMEcfs/fix  

###############################################
# Define the config file
###############################################
export CDAS_CONFIG_FILE=${CDAS_CONFIG_FILE:-$PARMcfs/cfs_parm_am/cfs_cdas_config}

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY

export CDATE=${CDATE:-${PDY}$cyc}

##############################################
# Define COM directories
##############################################
export COMROT=$COMROOT/${NET}/${envir}
export  COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
mkdir -m775 -p $COMOUT

export COMINIC=$COMROT/cdas.$PDYm1

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-${GESROOT}/${envir}}
export GESdir=$gespath/cdas.${PDY}
export RESDIR=${RESDIR:-$GESdir}
mkdir -p $RESDIR

##env

#############################################################
# execute the updated fit script for cfs and gfs
#############################################################

fitdir=$HOMEcfs/Fit2Obs/batrun
TMPDIR=$DATAROOT/fit2obs.$$; mkdir -p $TMPDIR

export OMP_NUM_THREADS=${FITOMP:-1}
export MPIRUN="mpirun -n 3"
export KMP_AFFINITY=disabled

export KEEPDATA=YES 

export NEMS=${NEMS:-YES}   
export PRVT=${PRVT:-$HOMEcfs/fix/cfs_fix_cdas/prepobs_errtable.global}
export HYBLEVS=${HYBLEVS:-$HOMEcfs/fix/cfs_fix_am/global_hyblev.l65.txt}

##############################################################
# run the fits for this time for the CFS and the GFS models 
##############################################################

for EXPNAM in CFS GFS; do
[[ $EXPNAM = GFS ]] && COMFIT=$COMROOT/gfs/prod
[[ $EXPNAM = GFS ]] && ACPROFit=YES  
[[ $EXPNAM = CFS ]] && COMFIT=$COMROOT/cfs/prod
[[ $EXPNAM = CFS ]] && ACPROFit=NO 
ARCDIR=$DATA/$EXPNAM.fits
time $fitdir/runfits $EXPNAM $CDATE $COMFIT
err=$?; err_chk

# tar up the fits and save in COMROT/fit2obs

cd $ARCDIR
FITARC=$COMROT/fit2obs; mkdir -p $FITARC
tar -cf $FITARC/$EXPNAM.fits.$CDATE *
err=$?; err_chk

done

###################################################
# msg end of job and clean up temperary directory
###################################################
cat $pgmout
msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

