#!/bin/ksh
set -xa

export PS4='$SECONDS + '
date

# #### 06/12/2006 ##############################################
# SETUP CDAS TROPICAL CYCLONE QC/RELOCATION PROCESSING VARIABLES
# ##############################################################

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00

export jlogfile=${jlogfile:-/dev/null}

##########################
# Specify NET and RUN Name
##########################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY

export CDATE=${CDATE:-${PDY}$cyc}
##########################################################
# define cfs directories/scripts/executables            
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm 
export USHcfs=$HOMEcfs/ush  
export FIXcfs=$HOMEcfs/fix  

export HOMEdump=$HOMEcfs

export HOMEnst=$HOMEcfs/nstrtg.v1.1.1
export EXECnst=$HOMEnst/exec
export FIXnst=$HOMEnst/fix

##############################################
# Define COM directories
##############################################
export COMROT=$COMROOT/${NET}/${envir}
export  COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
mkdir -m 755 -p $COMOUT

##############################################
# Define some INPUT directories
##############################################

export DCOMROOT=/gpfs/dell1/nco/ops/dcom/prod   ## dells dcom
export TANK_GRIBFLDS=${TANK_GRIBFLDS:-$DCOMROOT}             
export COM_GDAS=${COM_GDAS:-$(compath.py com/gfs/prod)}
export COM_ENGICE=${COM_ENGICE:-$(compath.py com/omb/prod/sice)}       ## after 20190613
export COMGDAS=${COMGDAS:-$COM_GDAS/gdas.${PDY}/$cyc}
export COMGFS=${COMGFS:-$COM_GDAS/gfs.${PDY}/$cyc}

#export COM_GDAS=/gpfs/dell1/nco/ops/com/gfs/prod
#export COM_ENGICE=/gpfs/dell1/nco/ops/com/omb/prod/sice    ## after 20190613
#export COM_SSTOIQD=/gpfs/gp1/nco/ops/com/omb/prod/sstoiqd  ## will this go away ??
#export COMGDAS=$COM_GDAS/gdas.${PDY}/$cyc

########################################################################
# execute the script
# Set DUMP_FROM_PROD to NO if getting the dump files from /global/dump
########################################################################

export DUMP_FROM_PROD=${DUMP_FROM_PROD:-YES}

if [ "$DUMP_FROM_PROD" = NO ]
then
  ${DUMPDV:-$HOMEcfs/scripts/excfs_hpss_dump.sh.ecf} 
else
  ${DUMPSH:-$HOMEcfs/scripts/excfs_cdas_dump.sh.ecf}
fi

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT  
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

