#!/bin/ksh
set -xa

export PS4='$SECONDS + '
date

# #### 06/12/2006 ##############################################
# SETUP CDAS TROPICAL CYCLONE QC/RELOCATION PROCESSING VARIABLES
# ##############################################################

########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00

##########################
# Specify NET and RUN Name
##########################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY

export CDATE=${CDATE:-${PDY}$cyc}
##########################################################
# define cfs directories/scripts/executables
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm
export USHcfs=$HOMEcfs/ush
export FIXcfs=$HOMEcfs/fix

export HOMEdump=$HOMEcfs

export HOMEnst=$HOMEcfs/nstrtg.v1.1.1
export EXECnst=$HOMEnst/exec
export FIXnst=$HOMEnst/fix

export HOMEobsproc_dump=$HOMEbufr_dump 

##############################################
# Define COM directories
##############################################
export COMROT=$(compath.py -o ${NET}/${cfs_ver})
export  COMIN=$(compath.py -o ${NET}/${cfs_ver}/${RUN}.${PDY})
export COMOUT=$(compath.py -o ${NET}/${cfs_ver}/${RUN}.${PDY})
mkdir -m 755 -p $COMOUT

export COMINm1=$COMROT/${RUN}.${PDYm1}  # for prev day snowdepth.global.grb

##############################################
# Define some INPUT directories
##############################################

#export COM_GDAS=${COM_GDAS:-$(compath.py $envir/com/gfs/${gfs_ver})}
export COM_GDAS=${COM_GDAS:-$(compath.py obsproc/$obsproc_ver)}
export COMGDAS=${COMGDAS:-${COM_GDAS}/gdas.${PDY}/${cyc}/atmos}

#export COM_ENGICE=${COM_ENGICE:-$(compath.py $envir/com/omb/${omb_ver}/sice)}       ## after 20190613
export COM_ENGICE=${COM_ENGICE:-$(compath.py seaice_analysis/${seaice_analysis_ver})/seaice_analysis}       ## after 20190613

#export COMGFS=${COMGFS:-${COM_GDAS}/gfs.${PDY}/${cyc}/atmos}
export COMGFS=${COMGFS:-$(compath.py gfs/$gfs_ver)/gfs.${PDY}/${cyc}/atmos}

export COMTC=${COMTC:-$(compath.py gfs/$gfs_ver)/gdas.${PDY}/${cyc}/atmos} 
########################################################################
# execute the script
# Set DUMP_FROM_PROD to NO if getting the dump files from /global/dump
########################################################################

export DUMP_FROM_PROD=${DUMP_FROM_PROD:-YES}

if [ "$DUMP_FROM_PROD" = NO ]
then
${DUMPDV:-$HOMEcfs/scripts/excfs_hpss_dump.sh}
else
${DUMPSH:-$HOMEcfs/scripts/excfs_cdas_dump.sh}
fi

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

