#!/bin/sh

set -xa

##########################################################
# obtain unique process id (pid) and make temp directory
##########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export NET=cfs

####################################
# Determine Job Output Name on System
####################################

export jlogfile=${jlogfile:-/dev/null}
export pgmout="OUTPUT.${pid}"

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
sh setpdy.sh
. ./PDY

##########################################################
# define cfs directories/scripts/executables            
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm 
export USHcfs=$HOMEcfs/ush  
export FIXcfs=$HOMEcfs/fix  

#############################################################
# execute the script
#############################################################
${CFSCLEANUPSH:-$HOMEcfs/scripts/excfs_switch.sh}
err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

