#!/bin/ksh
set -xa


####################################
# Specify NET and RUN Name and model
####################################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

export host=${host:-`hostname | cut -c1`}

date
export PS4='$SECONDS + '

# #############################################
# SETUP FITS TO OBS PROCESSING VARIABLES
# ##############################################

##########################################################
# obtain unique process id (pid) and make temp directory
##########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# VERBOSE  - Specify Verbose Output 
####################################
export VERBOSE=${VERBOSE:-YES}

##########################################################
# define cfs directories/scripts/executables            
##########################################################

export EXECcfs=$HOMEcfs/exec
export PARMcfs=$HOMEcfs/parm 
export USHcfs=$HOMEcfs/ush  
export FIXcfs=$HOMEcfs/fix  

###############################################
# Define the config file
###############################################
export CDAS_CONFIG_FILE=${CDAS_CONFIG_FILE:-$PARMcfs/cfs_parm_am/cfs_cdas_config}

##############################
# Run setpdy and initialize PDY variables
##############################
sh setpdy.sh
. ./PDY

export CDATE=${CDATE:-${PDY}$cyc}

##############################################
# Define COM directories
##############################################
export COMROT=$COMROOT/${NET}/${envir}
export  COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
mkdir -m775 -p $COMOUT

export COMINIC=$COMROT/cdas.$PDYm1

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-${GESROOT}/${envir}}
export GESdir=$gespath/cdas.${PDY}
mkdir -m 775 -p $GESdir

export RESDIR=${RESDIR:-$GESdir}
mkdir -p $RESDIR

env

#############################################################
# execute the script
#############################################################

for cyc in 00 06 12 18
do
  export cycle=t${cyc}z
  export CDATE=${PDY}$cyc
  ${VRFYFITSSH:-$HOMEcfs/scripts/excfs_cdas_vrfyfits.sh.ecf}
  err=$?; err_chk
done

###################################################
# msg end of job and clean up temperary directory
###################################################
cat $pgmout
msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

