#!/bin/bash
set -xau

####################################
# Specify NET and RUN Name and model
####################################
export NET=cfs
export RUN=cdas
export RUN1=cdas1

export host=${host:-`hostname | cut -c1`}
export jlogfile=${jlogfile:-/dev/null}

###############################################
# SETUP CDAS POST PROCESSING VARIABLES
###############################################
export PS4='$SECONDS + '
date

##########################################################
# obtain unique process id (pid) and make temp directory
##########################################################
export pid=$$
export DATA=$DATAROOT/$job.$pid
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################

export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}
export OMP_NUM_THREADS=1

####################################
# Specify cfs directories
#####################################

export EXECcfs=${EXECcfs:-$HOMEcfs/exec}
export FIXcfs=${FIXcfs:-$HOMEcfs/fix}
export USHcfs=${USHcfs:-$HOMEcfs/ush}
export PARMcfs=${PARMcfs:-$HOMEcfs/parm}

#################################################
# Define location of specific scripts/executables
#################################################

export HOMEgsm=${HOMEgsm:-$HOMEcfs/global_shared_cfs}
export HOMEpost=${HOMEpost:-$HOMEcfs/global_shared_cfs}

export CHGRESSH=${CHGRESSH:-$HOMEgsm/ush/global_chgres.sh}
export SIGHDR=${SIGHDR:-$HOMEgsm/exec/global_sighdr}

export NWPROD=$HOMEpost
export POSTGPSH=${POSTGPSH:-$HOMEpost/ush/global_nceppost.sh}
export POSTGPEXEC=${POSTGPEXEC:-$HOMEpost/exec/ncep_post}
export GENPSICHIEXE=${GENPSICHIEXE:-$HOMEcfs/exec/cfs_genpsiandchi}
export OVERPARMEXEC=${OVERPARMEXEC:-$HOMEcfs/exec/cfs_overparm_grib}

#########################################
# Run setpdy and initialize PDY variables
#########################################

sh setpdy.sh
. ./PDY

##############################################
# Define COM directories
##############################################

export COMROT=$(compath.py -o ${NET}/${cfs_ver})
export  COMIN=$(compath.py -o ${NET}/${cfs_ver}/${RUN}.${PDY})
export COMOUT=$(compath.py -o ${NET}/${cfs_ver}/${RUN}.${PDY})
mkdir -m775 -p $COMOUT

####################################
# Specify Forecast Hour Range
####################################
export SHOUR=00
export FHOUR=09
export FHOUT=01

####################################
# Specify Special Post Vars
####################################
export IGEN_ANL=${IGEN_ANL:-197}
export IGEN_FCST=${IGEN_FCST:-197}
export IGEN_OCNP=${IGEN_OCNP:-197}
export post_times="00 01 02 03 04 05 06 07 08 09"

##########################################################
# Specify variable to directly output pgrb files for GDAS
##########################################################
export LATCH=${LATCH:-8}
export LSOIL=${LSOIL:-4}
export IDSL=${IDSL:-2}
export CCPOST=${CCPOST:-YES}
export JO=${JO:-361}
export IO=${IO:-720}
export IDRT=${IDRT:-0}
export LONB=${LONB:-720}
export LATB=${LATB:-361}

export CAT_FLX_TO_PGB=${CAT_FLX_TO_PGB:-YES}

###########################
# Specify Output layers
###########################
export POSTGPVARS=${POSTGPVARS:-"KPO=37,PO=1000.,975.,950.,925.,900.,875.,850.,825.,800.,775.,750.,700.,650.,600.,550.,500.,450.,400.,350.,300.,250.,225.,200.,175.,150.,125.,100.,70.,50.,30.,20.,10.,7.,5.,3.,2.,1.,KTH=16,TH=270.,280.,290.,300.,310.,320.,330.,350.,400.,450.,550.,650.,850.,1000.,1250.,1500.,"}

#######################################
# Specify Restart File Name to Key Off
######################################
restart_file=${restart_file:-$COMIN/${RUN1}.t${cyc}z.logf}

####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=${SLEEP_TIME:-900}
export SLEEP_INT=${SLEEP_INT:-5}

env

###############################
# Various script parmeters
###############################

export GRIBVERSION=grib1
export OCNDIR=$COMOUT

export REDOUT='1>>'
export REDERR='2>'

###############################
# Execute the Script
###############################

${CFSNCEPPOSTSH:-$HOMEcfs/scripts/excfs_cdas_nceppost.sh}
err=$?; err_chk

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi


date

