#!/bin/ksh
#BSUB -J jcfs_cdas_dump_06
#BSUB -oo /ptmp/Yuqiu.Zhu/com/output/prod/today/cfs_cdas_dump_06.%J
#BSUB -eo /ptmp/Yuqiu.Zhu/com/output/prod/today/cfs_cdas_dump_06.%J
#BSUB -n 1
#BSUB -q "dev"
#BSUB -W 0:30
#BSUB -cwd /ptmp/Yuqiu.Zhu/tmpnwprd

export MP_TASK_AFFINITY=cpu
export envir=dev
export RUN_ENVIR=devpara
export cyc=06
export job=jcfs_cdas_dump_06

export PDY=20130220
#export DCOMROOT=/dcom_p6

# CALL executable job script here
/climate/save/Yuqiu.Zhu/CFSV2/jobs/JCFS_CDAS_DUMP
