#!/bin/bash
 
#-----------------------------------------------------
# Run the fire2mdl program on WCOSS Dell
#
# Invoke this script as follows:
# cat $script | bsub
#-----------------------------------------------------

#BSUB -oo fire2mdl.log
#BSUB -eo fire2mdl.log
#BSUB -q debug
#BSUB -R affinity[core(1)]
#BSUB -J fire2mdl
#BSUB -P NAM-T2O
#BSUB -cwd .
#BSUB -W 0:02

set -x

module purge
module load EnvVars/1.0.2
module load ips/18.0.1.163

rundir=${LS_SUBCWD}
execdir=${rundir}/../../exec

WORK="/gpfs/dell1/stmp/$LOGNAME/fire2mdl"
rm -fr $WORK
mkdir -p $WORK
cd $WORK

EXE=${execdir}/emcsfc_fire2mdl

#------------------------------------------------------------
# input/output files are set in the namelist. 
#------------------------------------------------------------

ln -fs ${rundir}/config.wcoss.dell.nml   ./fort.41

#------------------------------------------------------------
# Run executable.
#------------------------------------------------------------

$EXE

exit 0
