#!/bin/ksh
#BSUB -J jcfs_cdas_preciplis_00
##BSUB -a poe
#BSUB -oo /ptmp/Yuqiu.Zhu/com/output/prod/today/cfs_cdas_preciplis_00.o%J
#BSUB -eo /ptmp/Yuqiu.Zhu/com/output/prod/today/cfs_cdas_preciplis_00.o%J
#BSUB -cwd /ptmp/Yuqiu.Zhu/tmpnwprd
#BSUB -n 1
#BSUB -q "dev"
#BSUB -W 01:30

export envir=dev
export RUN_ENVIR=devpara
export cyc=00
export job=jcfs_cdas_preciplis_00

export PDY=20130220
/climate/save/Yuqiu.Zhu/CFSV2/jobs/JCFS_CDAS_PRECIPLIS
