#!/bin/ksh

#-----------------------------------------------------
# Run the sfcupdate program for a fire wx case
# on wcoss phase 1.
#
# Invoke this script as follows:
# cat run.wcoss.fire.lsf | bsub
#
# Do not run with more than one mpi task.
#-----------------------------------------------------

#BSUB -a poe
#BSUB -n 1
#BSUB -R rusage[mem=1500]
#BSUB -R affinity[core]
#BSUB -oo sfcupdate.log
#BSUB -eo sfcupdate.log
#BSUB -q dev_shared
#BSUB -J sfcupdate
#BSUB -P NDAS-T2O
#BSUB -cwd .
#BSUB -W 0:02

set -x

# path/name of the sfcupdate executable.
RUN_DIR=${LS_SUBCWD}
EXE_DIR=${RUN_DIR}/../../exec
EXE=$EXE_DIR/emcsfc_sfcupdate

WORK_DIR="/stmpp1/$LOGNAME/sfcupdate.fire"
rm -fr $WORK_DIR
mkdir -p $WORK_DIR
cd $WORK_DIR

DATA_DIR=/global/noscrub/George.Gayno/fire_case
ln -fs ${DATA_DIR}/ndas.t00z.input_nemsio.d01.tm12.20140810   ./
cp ndas.t00z.input_nemsio.d01.tm12.20140810 ndas.t00z.input_nemsio.d01.tm12.20140810_afterupdate
chmod 644 ndas.t00z.input_nemsio.d01.tm12.20140810_afterupdate

cp $DATA_DIR/fire.2014080912.daily.nam.grib2 ./
cp $DATA_DIR/fire.2014080912.monthly.nam.grib2 ./

# directory where fixed fields for nmmb grid are located.  includes landmask, albedo, greenness.
FIXED_DIR=$DATA_DIR

cat > ${WORK_DIR}/fort.41 << !
 &grid_info
  domain_name="nam"
 /
 &cycle
  cycle_year=2014
  cycle_month=08
  cycle_day=9
  cycle_hour=12
  fcst_hour=0.0
 /
 &model_flds
  first_guess_file="${WORK_DIR}/ndas.t00z.input_nemsio.d01.tm12.20140810"
  first_guess_file_type="nems"
 /
 &fixed_flds
  lsmask_file="${FIXED_DIR}/nam_slmask.grb"
 /
 &time_varying_analysis_flds
  snowfree_albedo_climo_file="${FIXED_DIR}/nam_snowfree_albedo.grb"
  greenfrc_climo_file="${FIXED_DIR}/nam_vegfrac.grb"
  z0_climo_file=""
  seaice_anal_dir="${WORK_DIR}"
  seaice_climo_file=""
  sst_anal_dir="${WORK_DIR}"
  sst_climo_file=""
  merge_coeff_sst=0.
  sst_anlcyc_update=.false.
  soilm_climo_file=""
  merge_coeff_soilm=99999.
  snow_depth_anal_dir="${WORK_DIR}"
  snow_depth_climo_file=""
  merge_coeff_snow_depth=0.
  fire_anal_dir="${WORK_DIR}"
 /
 &output
  output_file="./ndas.t00z.input_nemsio.d01.tm12.20140810_afterupdate"
  output_file_type="nems"
 /
 &settings
  thinned=.false.
  nsoil=4
 /

 &soil_parameters
  soil_type_src="statsgo"
  smclow = 0.5
  smchigh = 3.0
  smcmax = 0.395, 0.421, 0.434, 0.476, 0.476, 0.439,
           0.404, 0.464, 0.465, 0.406, 0.468, 0.457,
           0.464, -9.99,  0.20, 0.421
  beta =  4.05,  4.26,  4.74,  5.33,  5.33,  5.25,
          6.77,  8.72,  8.17, 10.73, 10.39, 11.55,
          5.25, -9.99,  4.05,  4.26
  psis =  0.0350, 0.0363, 0.1413, 0.7586, 0.7586, 0.3548,
          0.1349, 0.6166, 0.2630, 0.0977, 0.3236, 0.4677,
          0.3548,  -9.99, 0.0350, 0.0363
  satdk = 1.7600e-4, 1.4078e-5, 5.2304e-6, 2.8089e-6, 2.8089e-6,
          3.3770e-6, 4.4518e-6, 2.0348e-6, 2.4464e-6, 7.2199e-6,
          1.3444e-6, 9.7394e-7, 3.3770e-6,     -9.99, 1.4078e-5,
          1.4078e-5
 /
 &veg_parameters
  veg_type_src="igbp"
  salp = 4.0
  snup = 0.080, 0.080, 0.080, 0.080, 0.080, 0.020,
         0.020, 0.060, 0.040, 0.020, 0.010, 0.020,
         0.020, 0.020, 0.013, 0.013, 0.010, 0.020,
         0.020, 0.020
 /
!

mpirun.lsf $EXE 

exit 0
