#!/bin/ksh --login
 
#-----------------------------------------------------
# Run gridgen_sfc for the NAM grid on the WCOSS
# phase 1 nodes.
#
# Invoke this script as follows:
# "cat run.nam12km.igbp.lsf | bsub"
#-----------------------------------------------------

#BSUB -a poe
#BSUB -n 4
#BSUB -R rusage[mem=2000]
#BSUB -R affinity[core(1)]
#BSUB -R span[ptile=4]
#BSUB -oo nam12km.log
#BSUB -eo nam12km.log
#BSUB -q dev_shared
#BSUB -J gridgen_sfc
#BSUB -P NAM-T2O
#BSUB -cwd .
#BSUB -W 0:10

set -x

EXEC_DIR=${LS_SUBCWD}/../../../exec

EXEC=emcsfc_gridgen_sfc

WORK="/stmpp1/${LOGNAME}/nam12km"
rm -fr $WORK
mkdir -p $WORK
cd $WORK

cp ${EXEC_DIR}/$EXEC    ./

#------------------------------------------------------------
# input/output files are set in the namelist. 
#------------------------------------------------------------

ln -fs ${LS_SUBCWD}/nam12km.igbp.nml   ./fort.41

#------------------------------------------------------------
# Run executable.
#------------------------------------------------------------

mpirun.lsf ./$EXEC

exit 0
