#!/bin/ksh
 
#-----------------------------------------------------
# Invoke this script as follows:
# "cat run.polar.lsf | bsub"
#-----------------------------------------------------

#BSUB -a poe
#BSUB -n 1
#BSUB -R span[ptile=1]
#BSUB -R rusage[mem=2000]
#BSUB -R affinity[core]
#BSUB -oo polar.log
#BSUB -eo polar.log
#BSUB -q dev_shared
#BSUB -J gridgen_sfc
#BSUB -P RTMA-T2O
#BSUB -cwd .
#BSUB -W 0:05

set -x

EXEC_DIR=${LS_SUBCWD}/../../../exec

EXEC=emcsfc_gridgen_sfc

WORK="/stmpp1/$LOGNAME/polar"
rm -fr $WORK
mkdir -p $WORK
cd $WORK

cp ${EXEC_DIR}/$EXEC    ./

#------------------------------------------------------------
# input/output files are set in the namelist. 
#------------------------------------------------------------

ln -fs ${LS_SUBCWD}/polar.nml   ./fort.41

#------------------------------------------------------------
# Run executable.
#------------------------------------------------------------

mpirun.lsf ./$EXEC

exit 0
