#!/bin/sh
 
#-----------------------------------------------------
# Run gridgen_sfc for a conus nest on wcoss cray.
#
# Invoke this script as follows:
# "cat run.conus.cray.lsf | bsub"
#-----------------------------------------------------

#BSUB -oo conus.log
#BSUB -eo conus.log
#BSUB -q dev
#BSUB -J gridgen_sfc
#BSUB -P NAM-T2O
#BSUB -W 0:02
#BSUB -M 500
#BSUB -cwd .
#BSUB -extsched 'CRAYLINUX[]'

set -x

module list

EXEC_DIR=${LS_SUBCWD}/../../../exec

EXEC=emcsfc_gridgen_sfc

WORK="/gpfs/hps/stmp/${LOGNAME}/conus"
rm -fr $WORK
mkdir -p $WORK
cd $WORK

cp ${EXEC_DIR}/$EXEC    ./

#------------------------------------------------------------
# input/output files are set in the namelist. 
#------------------------------------------------------------

ln -fs ${LS_SUBCWD}/conus.cray.nml   ./fort.41

#------------------------------------------------------------
# Run executable.
#
# "-j 1" means no hyperthreading
# "-n"   is total number of tasks
# "-N"   is tasks per node
#------------------------------------------------------------

export NODES=1
# run with four mpi tasks
aprun -j 1 -n 4 -N 4  ./$EXEC
# run with only one mpi task
#aprun -j 1 -n 1 -N 1  ./$EXEC

exit 0
