#!/bin/ksh

set -xa

date
export PS4='$SECONDS + '

####################################
# Specify NET and RUN Name and model
####################################
export NET=gfs
export RUN=sst

####################################
# variables that control processing
# Determine variable settings before testing and set them accordingly
#    SENDDBN=YES        Issue DBNet Client Calls
#    SENDCOM=YES        copy files from TMPDIR to $COMOUT
####################################
 
export SENDDBN_GB2=${SENDDBN_GB2:-YES}

export DATA=$DATAROOT/${jobid}
mkdir -p $DATA
cd $DATA 
export TMPDIR=$DATA

export cycle=t${cyc}z

######################
# Set up the UTILITIES
######################
export HOMEutil=$UTILROOT
export EXECutil=$HOMEutil/exec
export FIXutil=$HOMEutil/fix
export PARMutil=$HOMEutil/parm
export USHutil=$HOMEutil/ush

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. PDY

####################################
# Determine Job Output Name on System
####################################
# JY export pgmout="OUTPUT.${pid}"
export pgmout="OUTPUT.$$"

#################################################
# Specify job's execution areas (directory paths)
#################################################
export EXECnstrtg=${EXECnstrtg:-$HOMEnstrtg/exec}
export FIXnstrtg=${FIXnstrtg:-$HOMEnstrtg/fix}
###################################################
# Set directories where this job's input is located
# using the COMIN variable
###################################################
export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}

export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}
mkdir -p $COMOUT

#export COM_SEAICE=/gpfs/dell1/nco/ops/com/omb/prod/sice
export COM_SEAICE=$(compath.py omb/prod/sice)

if [ "$envir" = "prod" ];then
  export pcom=${pcom:-${PCOMROOT}/${NET}}
elif [ "$envir" = "para" -o "$envir" = "test" ] ; then
  export pcom=${pcom:-${PCOMROOT}/${envir}/${NET}}
fi

export RUNTYPE=${RUNTYPE:-quasi_prod}

# Execute the script
$HOMErtgsst/scripts/exnstrtg.sh.ecf
###############################################

cat $pgmout

msg='ENDED NORMALLY.'
postmsg "$jlogfile" "$msg"

if [[ $KEEPDATA != YES && $KEEPDATA != yes ]] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

