#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export DATA=$DATAROOT/${jobid}
mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 

#
# Set up model and cycle specific variables
#
export NET=gfs
export RUN=sst
export EXT=""
export DBN_ALERT_TYPE=RTGSST_GEMPAK

#################################################
# Specify job's execution areas (directory paths)
#################################################
export EXECrtgsst=${EXECrtgsst:-$HOMErtgsst/exec}
export FIXrtgsst=${FIXrtgsst:-$HOMErtgsst/fix}
export PARMrtgsst=${PARMrtgsst:-$HOMErtgsst/parm}
export USHrtgsst=${USHrtgsst:-$HOMErtgsst/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=${UTILROOT}/ush
export utilities=${UTILROOT}/ush
export utilexec=${UTILROOT}/exec

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export com=${COMROOT}/${NET}/${envir}
export COMIN=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=${COMROOT}/nawips/${envir}/${RUN}.${PDY}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

export finc=3

########################################################
# Execute the script for the Atlantic Domain
export fend=0
export fstart=0
export GRIB="atl"
${HOMErtgsst}/scripts/exnawips_rtgssthr.sh.ecf
########################################################

########################################################
# Execute the script for the Pacific Domain
export fend=0
export fstart=0
export GRIB="pac"
${HOMErtgsst}/scripts/exnawips_rtgssthr.sh.ecf
########################################################

cat $pgmout

if [[ $KEEPDATA != YES && $KEEPDATA != yes ]] ; then
    cd $DATAROOT
    rm -rf $DATA
fi

date

