#!/bin/ksh
 
#--------------------------------------------------------
# Run the ice2mdl program on the WCOSS phase 2 nodes.
#
# Invoke this script as follows:
# "cat runit.wcoss.p2.lsf | bsub"
#--------------------------------------------------------

#BSUB -oo ice2mdl.log
#BSUB -eo ice2mdl.log
#BSUB -q dev2_shared
#BSUB -R rusage[mem=1500]
#BSUB -R affinity[core(1)]
#BSUB -J ice2mdl
#BSUB -P NAM-T2O
#BSUB -cwd .
#BSUB -W 0:02

set -x

rundir=${LS_SUBCWD}
execdir=${rundir}/../../exec

WORK="/stmpp2/$LOGNAME/ice2mdl"
rm -fr $WORK
mkdir -p $WORK
cd $WORK

cp ${execdir}/emcsfc_ice2mdl     ./

#------------------------------------------------------------
# input/output files are set in the namelist. 
#------------------------------------------------------------

ln -fs ${rundir}/config.wcoss.nml   ./fort.41

#------------------------------------------------------------
# Run executable.
#------------------------------------------------------------

./emcsfc_ice2mdl 

exit 0
