#!/bin/sh
 
#--------------------------------------------------------
# Run the ice2mdl program on the WCOSS Cray
#
# Invoke this script as follows:
# "cat runit.wcoss.cray.lsf | bsub"
#--------------------------------------------------------

#BSUB -oo ice2mdl.log
#BSUB -eo ice2mdl.log
#BSUB -q dev_shared
#BSUB -R rusage[mem=1500]
#BSUB -J ice2mdl
#BSUB -P NAM-T2O
#BSUB -cwd .
#BSUB -W 0:02

set -x

module list

rundir=${LS_SUBCWD}
execdir=${rundir}/../../exec

WORK="/gpfs/hps/stmp/$LOGNAME/ice2mdl"
rm -fr $WORK
mkdir -p $WORK
cd $WORK

cp ${execdir}/emcsfc_ice2mdl     ./

#------------------------------------------------------------
# input/output files are set in the namelist. 
#------------------------------------------------------------

ln -fs ${rundir}/config.wcoss.cray.nml   ./fort.41

#------------------------------------------------------------
# Run executable.
#------------------------------------------------------------

./emcsfc_ice2mdl 

exit 0
