#!/bin/bash

#--------------------------------------------------------
# Run coldstart program on WCOSS Dell to
# interpolate ndas land states to a nam grid.
#
# Invoke this script as follows:
# "cat $script | bsub"
#--------------------------------------------------------

#BSUB -oo log
#BSUB -eo log
#BSUB -M 3000
#BSUB -q debug
#BSUB -P NAM-T2O
#BSUB -J sfcupdate
#BSUB -W 0:05
#BSUB -x                  # not shared
#BSUB -n 1                # total tasks
#BSUB -R "span[ptile=1]"  # tasks per node
#BSUB -R "affinity[core(1):distribute=balance]"

set -x

module purge
module load EnvVars/1.0.2
module load ips/18.0.1.163
module load impi/18.0.1
module load lsf/10.1
module list

HOMEnam=/gpfs/gp1/nco/ops/nwprod/nam.v3.1.16

RUN_DIR=${LS_SUBCWD}
EXE_DIR=${RUN_DIR}/../../../exec
EXEC=${EXE_DIR}/emcsfc_coldstart
#EXEC=$HOMEnam/exec/nam_coldstart

WORK_DIR="/gpfs/dell1/stmp/$LOGNAME/coldstart.partialcyc"
mkdir -p $WORK_DIR
cd $WORK_DIR

FIXDIR=$HOMEnam/fix

# file with land states you want
INPUT_FILE=/gpfs/gp2/nco/ops/nwges/prod/nam.hold/nmm_b_restart_nemsio_hold.06z

# file with land states you want updated
cp /gpfs/gp2/nco/ops/nwges/prod/nam.20190117/nam.t12z.input_domain_01_nemsio.tm06_precoldstart  ./test_input_umo_regional.nemsio.d01 

cat > ./fort.41 << !
 &input_state_fields
  input_file="$INPUT_FILE"
  input_file_type="nems"
 /

 &output_grid_specs
  specs_from_output_file=.false.
  lats_output_file="${FIXDIR}/nam_hpnt_latitudes.grb"
  lons_output_file="${FIXDIR}/nam_hpnt_longitudes.grb"
  lsmask_output_file="${FIXDIR}/nam_slmask.grb"
  orog_output_file="${FIXDIR}/nam_elevtiles.grb"
  substrate_temp_output_file="${FIXDIR}/nam_tbot.grb"
 /

 &optional_output_fields
  snow_free_albedo_output_file=""
  greenfrc_output_file=""
  mxsnow_alb_output_file="${FIXDIR}/nam_mxsnoalb.grb"
  slope_type_output_file=""
  soil_type_output_file="${FIXDIR}/nam_soiltiles.grb"
  veg_type_output_file="${FIXDIR}/nam_vegtiles.grb"
  z0_output_file="${FIXDIR}/nam_z0clim.grb"
 /

 &soil_parameters
  soil_src_input = "statsgo"
  smclow_input  = 0.5
  smchigh_input = 3.0
  smcmax_input= 0.395, 0.421, 0.434, 0.476, 0.476, 0.439,
                0.404, 0.464, 0.465, 0.406, 0.468, 0.457,
                0.464, -9.99,  0.20, 0.421
  beta_input =  4.05,  4.26,  4.74,  5.33,  5.33,  5.25,
                6.77,  8.72,  8.17, 10.73, 10.39, 11.55,
                5.25, -9.99,  4.05,  4.26
  psis_input =  0.0350, 0.0363, 0.1413, 0.7586, 0.7586, 0.3548,
                0.1349, 0.6166, 0.2630, 0.0977, 0.3236, 0.4677,
                0.3548,  -9.99, 0.0350, 0.0363
  satdk_input = 1.7600e-4, 1.4078e-5, 5.2304e-6, 2.8089e-6, 2.8089e-6,
                3.3770e-6, 4.4518e-6, 2.0348e-6, 2.4464e-6, 7.2199e-6,
                1.3444e-6, 9.7394e-7, 3.3770e-6,     -9.99, 1.4078e-5,
                1.4078e-5
  soil_src_output = "statsgo"
  smclow_output  = 0.5
  smchigh_output = 3.0
  smcmax_output= 0.395, 0.421, 0.434, 0.476, 0.476, 0.439,
                 0.404, 0.464, 0.465, 0.406, 0.468, 0.457,
                 0.464, -9.99,  0.20, 0.421
  beta_output =  4.05,  4.26,  4.74,  5.33,  5.33,  5.25,
                 6.77,  8.72,  8.17, 10.73, 10.39, 11.55,
                 5.25, -9.99,  4.05,  4.26
  psis_output =  0.0350, 0.0363, 0.1413, 0.7586, 0.7586, 0.3548,
                 0.1349, 0.6166, 0.2630, 0.0977, 0.3236, 0.4677,
                 0.3548, -9.99,  0.0350, 0.0363
  satdk_output = 1.7600e-4, 1.4078e-5, 5.2304e-6, 2.8089e-6, 2.8089e-6,
                3.3770e-6, 4.4518e-6, 2.0348e-6, 2.4464e-6, 7.2199e-6,
                1.3444e-6, 9.7394e-7, 3.3770e-6,     -9.99, 1.4078e-5,
                1.4078e-5
 /
 &veg_parameters
  veg_src_input = "igbp"
  veg_src_output = "igbp"
  salp_output = 4.0
  snup_output = 0.080, 0.080, 0.080, 0.080, 0.080, 0.020,
                0.020, 0.060, 0.040, 0.020, 0.010, 0.020,
                0.020, 0.020, 0.013, 0.013, 0.010, 0.020,
                0.020, 0.020
 /
 &final_output
  output_file_type="nems"
  output_file="test_input_umo_regional.nemsio.d01"
 /
 &options
  landice_opt=3
 /
 &nam_options
  merge=.false.
 /
!

mpirun $EXEC

exit 0
